export const GENDER_CATEGORIES = ["Man", "Woman", "Kids"];
export const PRODUCT_CATEGORIES = [
  {
    category: "Shoes",
    subCategory: [
      "All shoes",
      "Air Force",
      "Running Shoes",
      "Basketball Shoes",
      "Football Boots",
      "Training Shoes",
      "Casual Shoes",
      "Sneakers",
      "Sandals",
      "Slides",
    ],
  },
  {
    category: "Clothing",
    subCategory: [
      "All clothing",
      "Hoodies",
      "T-Shirts",
      "Jackets",
      "Pants",
      "Shorts",
      "Sports Bras",
      "Leggings",
      "Sweatshirts",
      "Tank Tops",
      "Compression Wear",
    ],
  },
  {
    category: "Accessories",
    subCategory: [
      "All accessories",
      "Bag",
      "Caps",
      "Socks",
      "Belts",
      "Gloves",
      "Watches",
      "Headbands",
      "Water Bottles",
      "Phone Cases",
      "Sunglasses",
      "Backpacks",
    ],
  },
  {
    category: "Equipment",
    subCategory: [
      "All equipment",
      "Balls",
      "Yoga Mats",
      "Resistance Bands",
      "Dumbbells",
      "Jump Ropes",
      "Fitness Trackers",
      "Foam Rollers",
      "Gym Bags",
      "Training Cones",
      "Kettlebells",
    ],
  },
  {
    category: "Outerwear",
    subCategory: [
      "All outerwear",
      "Windbreakers",
      "Rain Jackets",
      "Puffer Jackets",
      "Gilets",
      "Fleeces",
      "Softshell Jackets",
      "Parkas",
      "Lightweight Jackets",
    ],
  },
];
